### PR TITLE
Added trashmail domains

### PR DESCRIPTION
**Pull request by kzuri**

### CODE REVIEW

**Comment by vyasriday** [comment]
@kzuri Thanks for reaching out. For hacktoberfest pull requests that are created during october will be considered. To become eligible for LoginRadius swags we will consider your contribution on our open source before october as well. :)  But unfortunately it won't be counted towards official hacktoberfest pull request count. I hope that resolves your query.

**Comment by kzuri** [comment]
Thank you @vyasriday for clarification. So, will this PR get merged?

**Comment by vyasriday** [comment]
@kzuri I have put the PR under review. We will let your know once it's merged.

**Comment by kzuri** [comment]
> 
> 
> @kzuri I have put the PR under review. We will let your know once it's merged.

AWESOME!!!

**Comment by kzuri** [comment]
@vyasriday any updates?

**Comment by pareek-narendra** [comment]
@kzuri Please rebase and resolve the conflicts in this PR.

**Comment by kzuri** [comment]
@pareek-narendra Review #33 and close this PR

**Pull request closed without merging**
