### PR TITLE
Custom Onet hostnames

### PR DESCRIPTION
**Pull request by Shanduur**
Hello.
I noticed, that some of the custom hostnames from Onet are missing. I wanted to add them. I hope this is helpful.

### CODE REVIEW

**Comment by code-vj** [comment]
@Shanduur looks like both "adexec.com" and  "adres.pl" is not valid

**Comment by Shanduur** [comment]
@code-vj Ok, I removed `adexec.com` although I didn't added this, just for sanity.

Also `adres.pl` IS VALID. Look, I can create free *onet.pl* account and choose *adres.pl* as my alias:

Screenshot 2020-10-13 071355
Screenshot 2020-10-13 071423

**Comment by Shanduur** [comment]
@aman-agrwl I would love to have someone to take a look at this once again.

**Comment by code-vj** [comment]
@Shanduur `adres.pl` looks Ok

**Pull request merged**
